import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import img from '../../public/Logo.svg'
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between lg:mx-[30px] mx-[10px] items-center py-[20px] border-b">
          <div className="flex gap-[30px] items-center">
            <Image src={img} alt="test" />
            <p className="lg:block hidden">Products</p>
            <p className="lg:block hidden">Solutions</p>
            <p className="lg:block hidden">Pricing</p>
            <p className="lg:block hidden">Resources</p>
          </div>

          <div className="flex gap-[20px] items-center">
            <button className="lg:block hidden">Log In</button>
            <button className="p-[10px] border rounded lg:block hidden">Sign Up Now</button>
            <button className="border p-[5px] rounded lg:hidden ">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>

        </div>
        {children}
      </body>
    </html>
  );
}
